### ISSUE TITLE
Matrix Reloaded

### ISSUE THREAD

**Issue by mrand** [home-assistant-community-themes/theme-request#10]
I'm publishing my updated Matrix theme, and would be happy to include it here.

# General information

**Owner**

me (@mrand)

**Name**

Matrix Reloaded

**Post link**

https://github.com/mrand/matrix_reloaded

**Comment by pho3nixf1re** [comment]
Are you still interested in including this here? If so I can work with you on that.

**Comment by mrand** [comment]
I'd be happy to if there is interest.

**Comment by pho3nixf1re** [comment]
I have recently been granted this org to help manage so I'm just now catching up and adjusting things to make it easier to manage. I rebased and pushed your code to the new repo https://github.com/home-assistant-community-themes/matrix-reloaded . You are the repo maintainer and should have full access to push and merge PRs. I will be making adjustments to the workflows and travis config in the coming weeks. Welcome to the party!

**Comment by pho3nixf1re** [comment]
Oh, and be sure to archive your old repo and update the README there to point to the new one here.
