### ISSUE TITLE
Home Assistant Neon glow themes

### ISSUE THREAD

**Issue by Welsyntoffie** [home-assistant-community-themes/theme-request#11]
# General information

**Owner**
Owner: Pieter Bezuidenhout
Link to github: https://github.com/Welsyntoffie/Neon_glow/tree/development

I plan to create multiple variations of the theme. Blue, Green, Yellow, Pink, Red

**Name**
neon_glows

**Post link**
Inspiration and starting point began from https://github.com/orickcorreia/caule-themes-pack-1. Thats where I got the idea to start a neon glow themes.

**Funding**
piter.bezuidenhout@gmail.com (PayPal)

# Screenshot(s)
![dash1](https://github.com/home-assistant-community-themes/theme-request/assets/47089904/4885327b-d933-4fc0-9dae-b25c370514b6)
![dash2](https://github.com/home-assistant-community-themes/theme-request/assets/47089904/b7a51e66-38f9-46a3-92cf-e68f917ee8d8)
![dash3](https://github.com/home-assistant-community-themes/theme-request/assets/47089904/f24258ad-0a55-4227-9128-4b130e56ec08)

# Source
Blue neon edge:
  # Header:
  # app-header-background-color: rgb(23, 23, 23)
  lovelace-background: 'center / cover no-repeat url("/hacsfiles/themes/blue_neon_edge/b1_blue.jpg") fixed'
  app-header-background-color: rgba(52, 170, 223,0.5)
  app-header-text-color: rgb(198, 203, 210)
  app-header-selection-bar-color: var(--primary-color)
  app-header-edit-background-color: rgb(136, 136, 136)
  # Main Interface Colors
  primary-color: rgb(138, 180, 248)
  primary-background-color: rgb(23, 23, 23)
  secondary-background-color: rgb(32, 33, 36)
  divider-color: var(--primary-background-color)
  accent-color: var(--primary-color)
  # Text
  primary-text-color: rgb(3, 255, 255)
  secondary-text-color: rgb(5, 163, 242)
  text-primary-color: var(--primary-text-color)
  disabled-text-color: rgba(184, 190, 199, 0.4)
  # Sidebar Menu
  sidebar-icon-color: rgb(52, 170, 223)
  sidebar-text-color: rgb(198, 203, 210)
  sidebar-background-color: rgb(32, 33, 36)
  sidebar-selected-icon-color: rgb(138, 180, 248)
  sidebar-selected-text-color: var(--sidebar-selected-icon-color)
  # Buttons
  paper-item-icon-color: rgb(169, 177, 188)
  paper-item-icon-active-color: rgb(138, 180, 248)
  mdc-button-outline-color: rgb(138, 180, 248)
  # States and Badges
  state-icon-color: var(--paper-item-icon-color)
  state-icon-active-color: var(--paper-item-icon-active-color)
  state-icon-unavailable-color: var(--disabled-text-color)
  # Sliders
  paper-slider-knob-color: rgb(52, 170, 223)
  paper-slider-knob-start-color: var(--paper-slider-knob-color)
  paper-slider-pin-color: var(--paper-slider-knob-color)
  paper-slider-active-color: var(--paper-slider-knob-color)
  paper-slider-secondary-color: var(--light-primary-color)
  # Labels
  label-badge-background-color: var(--secondary-background-color)
  label-badge-text-color: var(--primary-text-color)
  label-badge-red: rgb(208, 101, 104)
  label-badge-green: rgb(128, 200, 132)
  label-badge-blue: rgb(138, 180, 248)
  label-badge-yellow: rgb(223, 194, 113)
  label-badge-gray: rgb(95, 98, 103)
  # Cards
  ha-card-border-radius: 6px
  card-background-color: rgb(32, 33, 36)
  ha-card-background: rgba(0, 15, 20, 0.5)
  ha-card-border-color: rgb(42, 43, 46)
  ha-card-box-shadow: 0px 0px 6px 2px rgba(52, 170, 223,0.9)  
  paper-dialog-background-color: var(--card-background-color)
  paper-listbox-background-color: var(--card-background-color)
  paper-card-background-color: var(--card-background-color)
  # Switches
  switch-checked-button-color: rgb(52, 170, 223)
  switch-checked-track-color: rgb(138, 180, 248)
  switch-unchecked-button-color: rgb(172, 176, 185)
  switch-unchecked-track-color: rgb(154, 160, 166)
  # Toggles
  paper-toggle-button-checked-button-color: var(--switch-checked-button-color)
  paper-toggle-button-checked-bar-color: var(--switch-checked-track-color)
  paper-toggle-button-unchecked-button-color: var(--switch-unchecked-button-color)
  paper-toggle-button-unchecked-bar-color: var(--switch-unchecked-track-color)
  # Table
  table-row-background-color: var(--primary-background-color)
  table-row-alternative-background-color: var(--secondary-background-color)
  data-table-background-color: var(--primary-background-color)
  # Dropdowns
  material-background-color: var(--table-row-background-color)
  material-secondary-background-color: var(--table-row-alternative-background-color)
  mdc-theme-surface: var(--secondary-background-color)
  # Pre/Code
  markdown-code-background-color: rgb(23, 23, 23)
  code-editor-background-color: rgb(23, 23, 23)
  # Checkboxes
  mdc-checkbox-unchecked-color: rgb(169, 177, 188)
  mdc-checkbox-disable-color: var(--disabled-text-color)
  mdc-select-fill-color: rgb(42, 43, 46)
  mdc-select-ink-color: var(--primary-text-color)
  mdc-select-label-ink-color: var(--secondary-text-color)
  mdc-select-idle-line-color: var(--primary-text-color)
  mdc-select-dropdown-icon-color: var(--secondary-text-color)
  mdc-select-hover-line-color: var(--accent-color)
  mdc-text-field-fill-color: var(--mdc-select-fill-color)
  # Input
  input-fill-color: var(--secondary-background-color)
  input-dropdown-icon-color: var(--secondary-text-color)
  input-ink-color: var(--primary-text-color)
  input-label-ink-color: var(--secondary-text-color)
  input-idle-line-color: var(--primary-text-color)
  input-hover-line-color: var(--accent-color)
  #RGB
  rgb-primary-text-color: 169, 177, 188
  rgb-primary-color: 169, 177, 188

Image used for background...
![b1_blue](https://github.com/home-assistant-community-themes/theme-request/assets/47089904/04ee9cc6-84b2-4d3b-8849-e0764d8ffa72)

```yaml

```

**Comment by maartenpaauw** [comment]
You are already hosting your theme at your own GitHub. This organization is meant for non git hosted themes. Thereby I'm closing this request.

**Comment by Welsyntoffie** [comment]
o Ok, 
I thought I needed to do it like this to get it to show in HACS like caules theme, cause there is limited themes there.
[here](https://github.com/orickcorreia/caule-themes-pack-1) is the link to caule theme pack 1 github thats also in HACS.
I guess that's where the confusion started.
