### ISSUE TITLE
Darkish Theme

### ISSUE THREAD

**Issue by 78wesley** [home-assistant-community-themes/theme-request#4]
# General information

**Owner**

[78wesley](https://github.com/78wesley)

**Name**

Darkish Theme

**Post link**

https://github.com/78wesley/Darkish-Theme

**Funding**

# Screenshot(s)

Screenshots are in the repository and in the README.MD
https://github.com/78wesley/Darkish-Theme/tree/master/docs

# Source

[darkish.yaml](https://github.com/78wesley/Darkish-Theme/blob/master/themes/darkish.yaml)
```yaml

```

**Comment by maartenpaauw** [comment]
Looking good! Will pick it up ASAP. Probably Monday 👍

**Comment by 78wesley** [comment]
I've already post it on https://github.com/hacs/default

**Comment by 78wesley** [comment]
Can this issue be deleted?

**Comment by maartenpaauw** [comment]
Issues can only be closed. Not deleted.
