### ISSUE TITLE
Vaporwave Pink Theme

### ISSUE THREAD

**Issue by linsvensson** [home-assistant-community-themes/theme-request#5]
# General information

**Owner**
[linsvensson](https://github.com/linsvensson)

**Name**
Vaporwave Pink Theme

**Post link**
https://github.com/linsvensson/vaporwave-pink-theme

**Funding**

# Screenshot(s)

![Capture1](https://user-images.githubusercontent.com/5594088/72549551-3511e500-3891-11ea-8806-1248dd50f523.PNG)
![Capture2](https://user-images.githubusercontent.com/5594088/72564315-c09a6e80-38af-11ea-9d82-e62c3522fe18.PNG)

# Source

[vaporwave-pink-yaml](https://github.com/linsvensson/vaporwave-pink-theme/blob/master/themes/vaporwave-pink.yaml)

**Comment by maartenpaauw** [comment]
Good looking theme! I've invited you to the organisation. Once you accepted the invitation you can transfer the repository to the organisation.

**Comment by maartenpaauw** [comment]
Nice it's transferred! I've added you as the theme maintainer.

**Comment by maartenpaauw** [comment]
I'll close this issue. Thanks for transferring. If you have any questions don't hesitate to ask them.
